<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Error propagation | Stats notes</title>
  <meta name="description" content="8 Error propagation | Stats notes" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Error propagation | Stats notes" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Error propagation | Stats notes" />
  
  
  

<meta name="author" content="Koen van Benthem" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="transforming-posterior-samples.html"/>
<link rel="next" href="proportion-of-negative-values-from-a-normal-distribution.html"/>
<script src="assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="assets/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Ramblings</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="differences-between-two-groups.html"><a href="differences-between-two-groups.html"><i class="fa fa-check"></i><b>2</b> Differences between two groups</a>
<ul>
<li class="chapter" data-level="2.1" data-path="differences-between-two-groups.html"><a href="differences-between-two-groups.html#notation"><i class="fa fa-check"></i><b>2.1</b> Notation</a></li>
<li class="chapter" data-level="2.2" data-path="differences-between-two-groups.html"><a href="differences-between-two-groups.html#t-test"><i class="fa fa-check"></i><b>2.2</b> t-test</a></li>
<li class="chapter" data-level="2.3" data-path="differences-between-two-groups.html"><a href="differences-between-two-groups.html#anova"><i class="fa fa-check"></i><b>2.3</b> ANOVA</a></li>
<li class="chapter" data-level="2.4" data-path="differences-between-two-groups.html"><a href="differences-between-two-groups.html#linear-model"><i class="fa fa-check"></i><b>2.4</b> linear model</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-test-and-t-test.html"><a href="correlation-test-and-t-test.html"><i class="fa fa-check"></i><b>3</b> Correlation test and t-test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="correlation-test-and-t-test.html"><a href="correlation-test-and-t-test.html#notation-1"><i class="fa fa-check"></i><b>3.1</b> Notation</a></li>
<li class="chapter" data-level="3.2" data-path="correlation-test-and-t-test.html"><a href="correlation-test-and-t-test.html#linear-model-1"><i class="fa fa-check"></i><b>3.2</b> Linear model</a></li>
<li class="chapter" data-level="3.3" data-path="correlation-test-and-t-test.html"><a href="correlation-test-and-t-test.html#correlation-test"><i class="fa fa-check"></i><b>3.3</b> Correlation test</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html"><i class="fa fa-check"></i><b>4</b> <span class="math inline">\(R^2\)</span> and correlation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#notation-2"><i class="fa fa-check"></i><b>4.1</b> Notation</a></li>
<li class="chapter" data-level="4.2" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#correlation-between-x-and-y"><i class="fa fa-check"></i><b>4.2</b> Correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span></a></li>
<li class="chapter" data-level="4.3" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#r2-value-of-the-linear-model"><i class="fa fa-check"></i><b>4.3</b> <span class="math inline">\(R^2\)</span> value of the linear model</a></li>
<li class="chapter" data-level="4.4" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#correlation-between-y-and-haty"><i class="fa fa-check"></i><b>4.4</b> Correlation between <span class="math inline">\(y\)</span> and <span class="math inline">\(\hat{y}\)</span></a></li>
<li class="chapter" data-level="4.5" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#r2-of-a-linear-regression-of-y-on-haty"><i class="fa fa-check"></i><b>4.5</b> <span class="math inline">\(R^2\)</span> of a linear regression of <span class="math inline">\(y\)</span> on <span class="math inline">\(\hat{y}\)</span></a></li>
<li class="chapter" data-level="4.6" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#r2-for-multiple-regression"><i class="fa fa-check"></i><b>4.6</b> <span class="math inline">\(R^2\)</span> for multiple regression</a></li>
<li class="chapter" data-level="4.7" data-path="r2-and-correlation.html"><a href="r2-and-correlation.html#r2-value-of-more-general-models"><i class="fa fa-check"></i><b>4.7</b> <span class="math inline">\(R^2\)</span> value of more general models</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>5</b> Survival analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="survival-analysis.html"><a href="survival-analysis.html#proportional-hazard-models"><i class="fa fa-check"></i><b>5.1</b> Proportional hazard models</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="when-not-to-use-a-pca.html"><a href="when-not-to-use-a-pca.html"><i class="fa fa-check"></i><b>6</b> When not to use a PCA</a></li>
<li class="chapter" data-level="7" data-path="transforming-posterior-samples.html"><a href="transforming-posterior-samples.html"><i class="fa fa-check"></i><b>7</b> Transforming posterior samples</a>
<ul>
<li class="chapter" data-level="7.1" data-path="transforming-posterior-samples.html"><a href="transforming-posterior-samples.html#binomial-model"><i class="fa fa-check"></i><b>7.1</b> Binomial model</a></li>
<li class="chapter" data-level="7.2" data-path="transforming-posterior-samples.html"><a href="transforming-posterior-samples.html#beta-zero-one-inflated-model"><i class="fa fa-check"></i><b>7.2</b> Beta zero one inflated model</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="error-propagation.html"><a href="error-propagation.html"><i class="fa fa-check"></i><b>8</b> Error propagation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="error-propagation.html"><a href="error-propagation.html#data-simulation"><i class="fa fa-check"></i><b>8.1</b> Data simulation</a></li>
<li class="chapter" data-level="8.2" data-path="error-propagation.html"><a href="error-propagation.html#problem-statement"><i class="fa fa-check"></i><b>8.2</b> Problem statement</a></li>
<li class="chapter" data-level="8.3" data-path="error-propagation.html"><a href="error-propagation.html#point-estimates"><i class="fa fa-check"></i><b>8.3</b> Point estimates</a></li>
<li class="chapter" data-level="8.4" data-path="error-propagation.html"><a href="error-propagation.html#uncertainty-using-sampling"><i class="fa fa-check"></i><b>8.4</b> Uncertainty using sampling</a></li>
<li class="chapter" data-level="8.5" data-path="error-propagation.html"><a href="error-propagation.html#uncertainty-using-delta-method"><i class="fa fa-check"></i><b>8.5</b> Uncertainty using delta method</a></li>
<li class="chapter" data-level="8.6" data-path="error-propagation.html"><a href="error-propagation.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="proportion-of-negative-values-from-a-normal-distribution.html"><a href="proportion-of-negative-values-from-a-normal-distribution.html"><i class="fa fa-check"></i><b>9</b> Proportion of negative values from a normal distribution</a>
<ul>
<li class="chapter" data-level="9.1" data-path="proportion-of-negative-values-from-a-normal-distribution.html"><a href="proportion-of-negative-values-from-a-normal-distribution.html#invariability-of-the-proportion-of-negative-values"><i class="fa fa-check"></i><b>9.1</b> Invariability of the proportion of negative values</a></li>
<li class="chapter" data-level="9.2" data-path="proportion-of-negative-values-from-a-normal-distribution.html"><a href="proportion-of-negative-values-from-a-normal-distribution.html#adapting-the-mean-to-find-a-given-proportion-of-negative-values"><i class="fa fa-check"></i><b>9.2</b> Adapting the mean to find a given proportion of negative values</a></li>
<li class="chapter" data-level="9.3" data-path="proportion-of-negative-values-from-a-normal-distribution.html"><a href="proportion-of-negative-values-from-a-normal-distribution.html#adapting-the-standard-deviation"><i class="fa fa-check"></i><b>9.3</b> Adapting the standard deviation</a></li>
<li class="chapter" data-level="9.4" data-path="proportion-of-negative-values-from-a-normal-distribution.html"><a href="proportion-of-negative-values-from-a-normal-distribution.html#simplified"><i class="fa fa-check"></i><b>9.4</b> Simplified</a></li>
<li class="chapter" data-level="9.5" data-path="proportion-of-negative-values-from-a-normal-distribution.html"><a href="proportion-of-negative-values-from-a-normal-distribution.html#matching-an-empirical-distribution"><i class="fa fa-check"></i><b>9.5</b> Matching an empirical distribution</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Stats notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="error-propagation" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Error propagation<a href="error-propagation.html#error-propagation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="data-simulation" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Data simulation<a href="error-propagation.html#data-simulation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this page, I will simulate some data. The data describes the number of visitors in one of two food trucks (A and B) over time.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="error-propagation.html#cb61-1" tabindex="-1"></a>timepoints <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">24</span></span>
<span id="cb61-2"><a href="error-propagation.html#cb61-2" tabindex="-1"></a>trucks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;A&#39;</span>,<span class="st">&#39;B&#39;</span>)</span>
<span id="cb61-3"><a href="error-propagation.html#cb61-3" tabindex="-1"></a></span>
<span id="cb61-4"><a href="error-propagation.html#cb61-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">time=</span>timepoints,<span class="at">truck=</span>trucks)</span>
<span id="cb61-5"><a href="error-propagation.html#cb61-5" tabindex="-1"></a></span>
<span id="cb61-6"><a href="error-propagation.html#cb61-6" tabindex="-1"></a>df<span class="sc">$</span>expected.visitors <span class="ot">&lt;-</span> <span class="fu">with</span>(df,<span class="fu">ifelse</span>(truck<span class="sc">==</span><span class="st">&#39;A&#39;</span>,<span class="fu">exp</span>(<span class="dv">3</span><span class="fl">-0.1</span><span class="sc">*</span>(time<span class="dv">-12</span>)<span class="sc">^</span><span class="dv">2</span>),<span class="fu">exp</span>(<span class="fl">3.2-0.07</span><span class="sc">*</span>(time<span class="dv">-18</span>)<span class="sc">^</span><span class="dv">2</span>)))</span></code></pre></div>
<p>We now have expected values for each truck at each time point.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="error-propagation.html#cb62-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb62-2"><a href="error-propagation.html#cb62-2" tabindex="-1"></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(<span class="at">x=</span>time,<span class="at">y=</span>expected.visitors,<span class="at">col=</span>truck)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">expand=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span><span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="errorprop_files/figure-html/unnamed-chunk-2-1.png" width="672" />
From this we can simulate data, by drawing from a poisson distribution. The final data that we will work with, looks like this:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="error-propagation.html#cb63-1" tabindex="-1"></a>df<span class="sc">$</span>visitors <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="fu">nrow</span>(df),df<span class="sc">$</span>expected.visitors)</span>
<span id="cb63-2"><a href="error-propagation.html#cb63-2" tabindex="-1"></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(<span class="at">x=</span>time,<span class="at">y=</span>visitors,<span class="at">col=</span>truck)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">expand=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span><span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="errorprop_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="problem-statement" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Problem statement<a href="error-propagation.html#problem-statement" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We proceed with a relatively simple quadratic model fit, to describe the patterns in the data:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="error-propagation.html#cb64-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(visitors<span class="sc">~</span>truck<span class="sc">*</span>time<span class="sc">+</span>truck<span class="sc">*</span><span class="fu">I</span>(time<span class="sc">^</span><span class="dv">2</span>),<span class="at">data=</span>df,<span class="at">family=</span>poisson)</span>
<span id="cb64-2"><a href="error-propagation.html#cb64-2" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = visitors ~ truck * time + truck * I(time^2), family = poisson, 
##     data = df)
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      -12.690334   2.113945  -6.003 1.94e-09 ***
## truckB            -7.994173   3.601178  -2.220   0.0264 *  
## time               2.632646   0.356181   7.391 1.45e-13 ***
## I(time^2)         -0.110190   0.014791  -7.450 9.35e-14 ***
## truckB:time       -0.007661   0.483004  -0.016   0.9873    
## truckB:I(time^2)   0.038036   0.017331   2.195   0.0282 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 540.32  on 49  degrees of freedom
## Residual deviance:  24.39  on 44  degrees of freedom
## AIC: 130.38
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>For this model, we are interested in the following:
- What is the maximum number of visitors at each truck at any hour.
- When does the maximum number of visitors arrive?
- How are these quantities different for the two trucks
- What is the uncertainty in each of the estimates 1–3.</p>
</div>
<div id="point-estimates" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Point estimates<a href="error-propagation.html#point-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Our model prediction (<span class="math inline">\(y\)</span>) for a specific truck <span class="math inline">\(i\)</span> at a specific time <span class="math inline">\(t\)</span> is (notation consistent with R):
<span class="math display">\[\begin{equation}
y = e^{\beta_{\text{Intercept}} + \beta_{\text{truckB}} \delta_{i,B} + \beta_{\text{time}}t + \beta_{\text{I(time^2)}}t^2 + \beta_{\text{truckB:time}}\delta_{i,B}t +  \beta_{\text{truckB:I(time^2)}}\delta_{i,B}t^2}
\end{equation}\]</span>
Here, <span class="math inline">\(\delta_{i,B}\)</span> is equal to 0 when we want to make an estimate for truck A (<span class="math inline">\(i=A\)</span>) and 1 when we want to make an estimate for truck B (<span class="math inline">\(i=B\)</span>). We now derive expressions for the maximum value and when this occurs. Note that because log transformations are monotonic, we can determine these points on the log scale. Or in other words, we can define a new quantity, <span class="math inline">\(\eta\)</span> which equals <span class="math inline">\(\log{y}\)</span>:
<span class="math display">\[\begin{equation}
\eta = \log{y} = {\beta_{\text{Intercept}} + \beta_{\text{truckB}} \delta_{i,B} + \beta_{\text{time}}t + \beta_{\text{I(time^2)}}t^2 + \beta_{\text{truckB:time}}\delta_{i,B}t +  \beta_{\text{truckB:I(time^2)}}\delta_{i,B}t^2}
\end{equation}\]</span>
whenever <span class="math inline">\(\eta\)</span> is at it’s highest possible value, so is <span class="math inline">\(y\)</span>. This occurs when <span class="math inline">\(\frac{\text{d}\eta}{\text{d}t}=0\)</span>. Hence, when:
<span class="math display">\[\begin{equation}
\frac{\text{d}\eta}{\text{d}t} =  \beta_{\text{time}} + 2\beta_{\text{I(time^2)}}t + \beta_{\text{truckB:time}}\delta_{i,B} +  2\beta_{\text{truckB:I(time^2)}}\delta_{i,B}t=0
\end{equation}\]</span>
Which can be solved for <span class="math inline">\(t\)</span> relatively easily:
<span class="math display">\[\begin{equation}
t_\text{max} = - \frac{\beta_{\text{time}}+ \beta_{\text{truckB:time}}\delta_{i,B}}{2(\beta_{\text{I(time^2)}} + \beta_{\text{truckB:I(time^2)}}\delta_{i,B})}
\end{equation}\]</span>
And for specific trucks, in this model we thus find:
<span class="math display">\[\begin{align}
t_\text{max,A} &amp;= - \frac{\beta_{\text{time}}}{2\beta_{\text{I(time^2)}}}\\
t_\text{max,B} &amp;= - \frac{\beta_{\text{time}}+ \beta_{\text{truckB:time}}}{2(\beta_{\text{I(time^2)}} + \beta_{\text{truckB:I(time^2)}})}
\end{align}\]</span>
The difference in maximum values is thus:
<span class="math display">\[\begin{equation}
\Delta t_\text{max} = \frac{\beta_{\text{time}}+ \beta_{\text{truckB:time}}}{2(\beta_{\text{I(time^2)}} + \beta_{\text{truckB:I(time^2)}})} - \frac{\beta_{\text{time}}}{2\beta_{\text{I(time^2)}}}
\end{equation}\]</span>
The corresponding maximum values of <span class="math inline">\(\eta\)</span> are then:
<span class="math display">\[\begin{align}
\eta_\text{max,A} &amp;= \beta_{\text{Intercept}} + \beta_{\text{time}} t_\text{max,A} + \beta_{\text{I(time^2)}}t_\text{max,A}^2 \\
\eta_\text{max,B} &amp;= \beta_{\text{Intercept}} + \beta_{\text{truckB}}  + (\beta_{\text{time}}+\beta_{\text{truckB:time}})t_\text{max,B} + (\beta_{\text{I(time^2)}}+\beta_{\text{truckB:I(time^2)}})t_\text{max,B}^2
\end{align}\]</span>
And the difference is thus:
<span class="math display">\[\begin{equation}
\Delta \eta_\text{max} = \beta_{\text{time}} (t_\text{max,A} - t_\text{max,B})+ \beta_{\text{I(time^2)}}(t_\text{max,A}^2 - t_\text{max,B}^2) -  \beta_{\text{truckB:time}}t_\text{max,B} - \beta_{\text{truckB:I(time^2)}}t_\text{max,B}^2
\end{equation}\]</span>
For the specific model fit, we end up with (for the time points):</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="error-propagation.html#cb66-1" tabindex="-1"></a>tmax.a <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">coef</span>(m1)[<span class="dv">3</span>]<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">coef</span>(m1)[<span class="dv">4</span>])</span>
<span id="cb66-2"><a href="error-propagation.html#cb66-2" tabindex="-1"></a>tmax.b <span class="ot">&lt;-</span> <span class="sc">-</span>(<span class="fu">coef</span>(m1)[<span class="dv">3</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">5</span>])<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(<span class="fu">coef</span>(m1)[<span class="dv">4</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">6</span>]))</span>
<span id="cb66-3"><a href="error-propagation.html#cb66-3" tabindex="-1"></a>Delta.time <span class="ot">&lt;-</span> tmax.a<span class="sc">-</span>tmax.b</span>
<span id="cb66-4"><a href="error-propagation.html#cb66-4" tabindex="-1"></a>tmax.a</span></code></pre></div>
<pre><code>##     time 
## 11.94595</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="error-propagation.html#cb68-1" tabindex="-1"></a>tmax.b</span></code></pre></div>
<pre><code>##     time 
## 18.19023</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="error-propagation.html#cb70-1" tabindex="-1"></a>tmax.a<span class="sc">-</span>tmax.b</span></code></pre></div>
<pre><code>##      time 
## -6.244285</code></pre>
<p>These values are close to the time points at which the maximum occurs in the two graphs! The difference between them is negative due to the maximum occurring later for truck B.</p>
<p>The corresponding maxima are then (on the log scale):</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="error-propagation.html#cb72-1" tabindex="-1"></a>eta.max.a <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1) <span class="sc">%*%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,tmax.a,tmax.a<span class="sc">^</span><span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb72-2"><a href="error-propagation.html#cb72-2" tabindex="-1"></a>eta.max.b <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1) <span class="sc">%*%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,tmax.b,tmax.b<span class="sc">^</span><span class="dv">2</span>,tmax.b,tmax.b<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-3"><a href="error-propagation.html#cb72-3" tabindex="-1"></a>delta.eta.max <span class="ot">&lt;-</span> eta.max.a <span class="sc">-</span> eta.max.b</span></code></pre></div>
<p>And on the response scale, that becomes:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="error-propagation.html#cb73-1" tabindex="-1"></a><span class="fu">exp</span>(eta.max.a)</span></code></pre></div>
<pre><code>##         [,1]
## [1,] 20.7883</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="error-propagation.html#cb75-1" tabindex="-1"></a><span class="fu">exp</span>(eta.max.b)</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 24.28934</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="error-propagation.html#cb77-1" tabindex="-1"></a><span class="fu">exp</span>(delta.eta.max)</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 0.8558611</code></pre>
<p>Note here that the last number corresponds to the ratio between the first two.</p>
</div>
<div id="uncertainty-using-sampling" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Uncertainty using sampling<a href="error-propagation.html#uncertainty-using-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Probably the easiest way to get some view of the uncertainty, is by sampling parameters.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="error-propagation.html#cb79-1" tabindex="-1"></a><span class="fu">library</span>(mvtnorm)</span>
<span id="cb79-2"><a href="error-propagation.html#cb79-2" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">rmvnorm</span>(<span class="fl">1e5</span>,<span class="fu">coef</span>(m1),<span class="fu">vcov</span>(m1)) <span class="co"># we draw 1e6 different parameter combinations</span></span>
<span id="cb79-3"><a href="error-propagation.html#cb79-3" tabindex="-1"></a></span>
<span id="cb79-4"><a href="error-propagation.html#cb79-4" tabindex="-1"></a><span class="co"># for each combination we calculate tmax values:</span></span>
<span id="cb79-5"><a href="error-propagation.html#cb79-5" tabindex="-1"></a>tmax.as <span class="ot">&lt;-</span> <span class="sc">-</span>samples[,<span class="dv">3</span>]<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>samples[,<span class="dv">4</span>])</span>
<span id="cb79-6"><a href="error-propagation.html#cb79-6" tabindex="-1"></a>tmax.bs <span class="ot">&lt;-</span> <span class="sc">-</span>(samples[,<span class="dv">3</span>]<span class="sc">+</span>samples[,<span class="dv">5</span>])<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(samples[,<span class="dv">4</span>]<span class="sc">+</span>samples[,<span class="dv">6</span>]))</span>
<span id="cb79-7"><a href="error-propagation.html#cb79-7" tabindex="-1"></a>delta.tmaxs <span class="ot">&lt;-</span> tmax.as <span class="sc">-</span> tmax.bs</span>
<span id="cb79-8"><a href="error-propagation.html#cb79-8" tabindex="-1"></a></span>
<span id="cb79-9"><a href="error-propagation.html#cb79-9" tabindex="-1"></a><span class="co"># confints:</span></span>
<span id="cb79-10"><a href="error-propagation.html#cb79-10" tabindex="-1"></a><span class="fu">quantile</span>(tmax.as,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 11.53233 12.35906</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="error-propagation.html#cb81-1" tabindex="-1"></a><span class="fu">quantile</span>(tmax.bs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 17.76564 18.64343</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="error-propagation.html#cb83-1" tabindex="-1"></a><span class="fu">quantile</span>(delta.tmaxs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##      2.5%     97.5% 
## -6.853705 -5.654158</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="error-propagation.html#cb85-1" tabindex="-1"></a><span class="co"># we can do the same for eta max:</span></span>
<span id="cb85-2"><a href="error-propagation.html#cb85-2" tabindex="-1"></a>eta.max.as <span class="ot">&lt;-</span> samples[,<span class="dv">1</span>] <span class="sc">+</span> samples[,<span class="dv">3</span>] <span class="sc">*</span> tmax.as <span class="sc">+</span> samples[,<span class="dv">4</span>] <span class="sc">*</span> tmax.as<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb85-3"><a href="error-propagation.html#cb85-3" tabindex="-1"></a>eta.max.bs <span class="ot">&lt;-</span> samples[,<span class="dv">1</span>] <span class="sc">+</span> samples[,<span class="dv">2</span>] <span class="sc">+</span> (samples[,<span class="dv">3</span>]<span class="sc">+</span>samples[,<span class="dv">5</span>]) <span class="sc">*</span> tmax.bs <span class="sc">+</span> (samples[,<span class="dv">4</span>]<span class="sc">+</span>samples[,<span class="dv">6</span>]) <span class="sc">*</span> tmax.bs<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb85-4"><a href="error-propagation.html#cb85-4" tabindex="-1"></a>delta.maxs <span class="ot">&lt;-</span> eta.max.as <span class="sc">-</span> eta.max.bs</span>
<span id="cb85-5"><a href="error-propagation.html#cb85-5" tabindex="-1"></a></span>
<span id="cb85-6"><a href="error-propagation.html#cb85-6" tabindex="-1"></a><span class="co"># confints:</span></span>
<span id="cb85-7"><a href="error-propagation.html#cb85-7" tabindex="-1"></a><span class="fu">quantile</span>(eta.max.as,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 2.811468 3.266305</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="error-propagation.html#cb87-1" tabindex="-1"></a><span class="fu">quantile</span>(eta.max.bs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 2.998823 3.387557</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="error-propagation.html#cb89-1" tabindex="-1"></a><span class="fu">quantile</span>(delta.maxs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##       2.5%      97.5% 
## -0.4534911  0.1446363</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="error-propagation.html#cb91-1" tabindex="-1"></a><span class="co"># on the response scale:</span></span>
<span id="cb91-2"><a href="error-propagation.html#cb91-2" tabindex="-1"></a><span class="fu">quantile</span>(<span class="fu">exp</span>(eta.max.as),<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 16.63433 26.21430</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="error-propagation.html#cb93-1" tabindex="-1"></a><span class="fu">quantile</span>(<span class="fu">exp</span>(eta.max.bs),<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 20.06191 29.59356</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="error-propagation.html#cb95-1" tabindex="-1"></a><span class="fu">quantile</span>(<span class="fu">exp</span>(delta.maxs),<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 0.635406 1.155619</code></pre>
</div>
<div id="uncertainty-using-delta-method" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Uncertainty using delta method<a href="error-propagation.html#uncertainty-using-delta-method" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now, we will approximate the 95% CIs using the delta method. This method is very nicely described by <span class="citation">Cooch and White (<a href="#ref-deltamethod">2024</a>)</span> . Recall the expression for the time at which the maximum occurs for truck A:
<span class="math display">\[\begin{equation}
\hat{t_\text{max,A}} = - \frac{\beta_{\text{time}}}{2\beta_{\text{I(time^2)}}}
\end{equation}\]</span>
For the delta method, we need to find the set of partial derivatives of <span class="math inline">\(\hat{t_\text{max,A}}\)</span> with respect to each of the model parameters:
<span class="math display">\[\begin{align}
\frac{\partial \hat{t_\text{max,A}}}{\partial \beta_{\text{Intercept}}} &amp;= 0\\
\frac{\partial \hat{t_\text{max,A}}}{\partial \beta_{\text{truckB}}} &amp;= 0\\
\frac{\partial \hat{t_\text{max,A}}}{\partial \beta_{\text{time}}} &amp;=  - \frac{1}{2\beta_{\text{I(time^2)}}}\\
\frac{\partial \hat{t_\text{max,A}}}{\partial \beta_{\text{I(time^2)}}} &amp;= \frac{\beta_{\text{time}}}{2\beta_{\text{I(time^2)}}^2}\\
\frac{\partial \hat{t_\text{max,A}}}{\partial \beta_{\text{truckB:time}}} &amp;= 0\\

\frac{\partial \hat{t_\text{max,A}}}{\partial \beta_{\text{truckB:I(time^2)}}} &amp;= 0\\


\end{align}\]</span>
In slightly shorter notation, we can write:
<span class="math display">\[\begin{equation}
\nabla \hat{t_\text{max,A}} = \begin{bmatrix} 0 \\ 0 \\ - \frac{1}{2\beta_{\text{I(time^2)}}} \\  \frac{\beta_{\text{time}}}{2\beta_{\text{I(time^2)}}^2} \\ 0 \\ 0 \end{bmatrix}
\end{equation}\]</span>
We can get to the uncertainty using this expression together with the variance covariance matrix (<span class="math inline">\(\Sigma\)</span>):
<span class="math display">\[\begin{equation}
\text{Var}(\hat{t_\text{max,A}}) = \nabla \hat{t_\text{max,A}}^\text{T} \cdot \Sigma \cdot \nabla \hat{t_\text{max,A}}
\end{equation}\]</span>
We can take the square root of this variance to obtain the standard error, and then approximate the 95% CI using this standard error. In R notation:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="error-propagation.html#cb97-1" tabindex="-1"></a>vcv <span class="ot">&lt;-</span> <span class="fu">vcov</span>(m1) <span class="co"># get vcv</span></span>
<span id="cb97-2"><a href="error-propagation.html#cb97-2" tabindex="-1"></a>derivs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">coef</span>(m1)[<span class="dv">4</span>]), <span class="fu">coef</span>(m1)[<span class="dv">3</span>]<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">coef</span>(m1)[<span class="dv">4</span>]<span class="sc">^</span><span class="dv">2</span>),<span class="dv">0</span>,<span class="dv">0</span>) <span class="co"># gradient</span></span>
<span id="cb97-3"><a href="error-propagation.html#cb97-3" tabindex="-1"></a></span>
<span id="cb97-4"><a href="error-propagation.html#cb97-4" tabindex="-1"></a><span class="co"># uncertainty (variance):</span></span>
<span id="cb97-5"><a href="error-propagation.html#cb97-5" tabindex="-1"></a>var.tmax.a <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(derivs<span class="sc">%*%</span> vcv <span class="sc">%*%</span> derivs)</span>
<span id="cb97-6"><a href="error-propagation.html#cb97-6" tabindex="-1"></a>se.tmax.a <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var.tmax.a)</span>
<span id="cb97-7"><a href="error-propagation.html#cb97-7" tabindex="-1"></a></span>
<span id="cb97-8"><a href="error-propagation.html#cb97-8" tabindex="-1"></a><span class="co"># 95% CI:</span></span>
<span id="cb97-9"><a href="error-propagation.html#cb97-9" tabindex="-1"></a>tmax.a.CI <span class="ot">&lt;-</span> tmax.a <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))<span class="sc">*</span>se.tmax.a</span>
<span id="cb97-10"><a href="error-propagation.html#cb97-10" tabindex="-1"></a>tmax.a.CI</span></code></pre></div>
<pre><code>## [1] 11.54967 12.34222</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="error-propagation.html#cb99-1" tabindex="-1"></a><span class="co"># compare to the sampling 95% CI:</span></span>
<span id="cb99-2"><a href="error-propagation.html#cb99-2" tabindex="-1"></a><span class="fu">quantile</span>(tmax.as,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 11.53233 12.35906</code></pre>
<p>We can calculate the CI for <span class="math inline">\(t_\text{max,B}\)</span> anaogously:
<span class="math display">\[\begin{equation}
\nabla \hat{t_\text{max,B}} = \begin{bmatrix} 0 \\ 0 \\
- \frac{1}{2(\beta_{\text{I(time^2)}}+\beta_{\text{truckB:I(time^2)}})} \\  
\frac{\beta_{\text{time}}+\beta_{\text{truckB:time}}}{2(\beta_{\text{I(time^2)}}+\beta_{\text{truckB:I(time^2)}})^2} \\ - \frac{1}{2(\beta_{\text{I(time^2)}}+\beta_{\text{truckB:I(time^2)}})} \\ \frac{\beta_{\text{time}}+\beta_{\text{truckB:time}}}{2(\beta_{\text{I(time^2)}}+\beta_{\text{truckB:I(time^2)}})^2}
\end{bmatrix}
\end{equation}\]</span>
and:
<span class="math display">\[\begin{equation}
\text{Var}(\hat{t_\text{max,B}}) = \nabla \hat{t_\text{max,B}}^\text{T} \cdot \Sigma \cdot \nabla \hat{t_\text{max,B}}
\end{equation}\]</span>
From here it is then straightforward to calculate the standard error and 95% CI.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="error-propagation.html#cb101-1" tabindex="-1"></a>vcv <span class="ot">&lt;-</span> <span class="fu">vcov</span>(m1) <span class="co"># get vcv</span></span>
<span id="cb101-2"><a href="error-propagation.html#cb101-2" tabindex="-1"></a>derivs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(<span class="fu">coef</span>(m1)[<span class="dv">4</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">6</span>])), (<span class="fu">coef</span>(m1)[<span class="dv">3</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">5</span>])<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(<span class="fu">coef</span>(m1)[<span class="dv">4</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">6</span>])<span class="sc">^</span><span class="dv">2</span>),<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(<span class="fu">coef</span>(m1)[<span class="dv">4</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">6</span>])),(<span class="fu">coef</span>(m1)[<span class="dv">3</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">5</span>])<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(<span class="fu">coef</span>(m1)[<span class="dv">4</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">6</span>])<span class="sc">^</span><span class="dv">2</span>)) <span class="co"># gradient</span></span>
<span id="cb101-3"><a href="error-propagation.html#cb101-3" tabindex="-1"></a></span>
<span id="cb101-4"><a href="error-propagation.html#cb101-4" tabindex="-1"></a><span class="co"># uncertainty (variance):</span></span>
<span id="cb101-5"><a href="error-propagation.html#cb101-5" tabindex="-1"></a>var.tmax.b <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(derivs<span class="sc">%*%</span> vcv <span class="sc">%*%</span> derivs)</span>
<span id="cb101-6"><a href="error-propagation.html#cb101-6" tabindex="-1"></a>se.tmax.b <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var.tmax.b)</span>
<span id="cb101-7"><a href="error-propagation.html#cb101-7" tabindex="-1"></a></span>
<span id="cb101-8"><a href="error-propagation.html#cb101-8" tabindex="-1"></a><span class="co"># 95% CI:</span></span>
<span id="cb101-9"><a href="error-propagation.html#cb101-9" tabindex="-1"></a>tmax.b.CI <span class="ot">&lt;-</span> tmax.b <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))<span class="sc">*</span>se.tmax.b</span>
<span id="cb101-10"><a href="error-propagation.html#cb101-10" tabindex="-1"></a>tmax.b.CI</span></code></pre></div>
<pre><code>## [1] 17.76630 18.61416</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="error-propagation.html#cb103-1" tabindex="-1"></a><span class="co"># compare to the sampling 95% CI:</span></span>
<span id="cb103-2"><a href="error-propagation.html#cb103-2" tabindex="-1"></a><span class="fu">quantile</span>(tmax.bs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 17.76564 18.64343</code></pre>
<p>Next, we can do the same for the difference in time. We take a shortcut now, in the sense that we let R calculate the derivatives for us, using the Deriv library.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="error-propagation.html#cb105-1" tabindex="-1"></a><span class="fu">library</span>(Deriv)</span>
<span id="cb105-2"><a href="error-propagation.html#cb105-2" tabindex="-1"></a><span class="co"># we define a function that calculates delta t max:</span></span>
<span id="cb105-3"><a href="error-propagation.html#cb105-3" tabindex="-1"></a>delta.t.max.fun <span class="ot">&lt;-</span> <span class="cf">function</span>(beta<span class="fl">.0</span>,beta.B,beta.time,beta.Bxtime,beta.time2,beta.Bxtime2){</span>
<span id="cb105-4"><a href="error-propagation.html#cb105-4" tabindex="-1"></a>  (beta.time <span class="sc">+</span> beta.Bxtime)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(beta.time2<span class="sc">+</span>beta.Bxtime2)) <span class="sc">-</span> beta.time<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>beta.time2)</span>
<span id="cb105-5"><a href="error-propagation.html#cb105-5" tabindex="-1"></a>}</span>
<span id="cb105-6"><a href="error-propagation.html#cb105-6" tabindex="-1"></a><span class="co"># below, for each of the coefficients, a function for the derivative is dermined and that function is evaluated:</span></span>
<span id="cb105-7"><a href="error-propagation.html#cb105-7" tabindex="-1"></a>derivs <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">&quot;beta.0&quot;</span>,<span class="st">&quot;beta.B&quot;</span>,<span class="st">&quot;beta.time&quot;</span>,<span class="st">&quot;beta.time2&quot;</span>,<span class="st">&quot;beta.Bxtime&quot;</span>,<span class="st">&quot;beta.Bxtime2&quot;</span>), <span class="at">FUN =</span> <span class="cf">function</span>(x){ </span>
<span id="cb105-8"><a href="error-propagation.html#cb105-8" tabindex="-1"></a>  derfun <span class="ot">&lt;-</span> <span class="fu">Deriv</span>(delta.t.max.fun,x)</span>
<span id="cb105-9"><a href="error-propagation.html#cb105-9" tabindex="-1"></a>  <span class="fu">derfun</span>(<span class="at">beta.0=</span><span class="fu">coef</span>(m1)[<span class="dv">1</span>],<span class="at">beta.B=</span><span class="fu">coef</span>(m1)[<span class="dv">2</span>],</span>
<span id="cb105-10"><a href="error-propagation.html#cb105-10" tabindex="-1"></a>         <span class="at">beta.time=</span><span class="fu">coef</span>(m1)[<span class="dv">3</span>],<span class="at">beta.time2=</span><span class="fu">coef</span>(m1)[<span class="dv">4</span>],</span>
<span id="cb105-11"><a href="error-propagation.html#cb105-11" tabindex="-1"></a>         <span class="at">beta.Bxtime=</span><span class="fu">coef</span>(m1)[<span class="dv">5</span>],<span class="at">beta.Bxtime2=</span><span class="fu">coef</span>(m1)[<span class="dv">6</span>])</span>
<span id="cb105-12"><a href="error-propagation.html#cb105-12" tabindex="-1"></a>  })</span>
<span id="cb105-13"><a href="error-propagation.html#cb105-13" tabindex="-1"></a><span class="fu">Deriv</span>(delta.t.max.fun,<span class="st">&quot;beta.time&quot;</span>)</span></code></pre></div>
<pre><code>## function (beta.0, beta.B, beta.time, beta.Bxtime, beta.time2, 
##     beta.Bxtime2) 
## 1/(2 * (beta.Bxtime2 + beta.time2)) - 1/(2 * beta.time2)</code></pre>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="error-propagation.html#cb107-1" tabindex="-1"></a><span class="co"># In a similar fashion as before, we can no proceed and calculate the 95% CI:</span></span>
<span id="cb107-2"><a href="error-propagation.html#cb107-2" tabindex="-1"></a><span class="co"># uncertainty (variance):</span></span>
<span id="cb107-3"><a href="error-propagation.html#cb107-3" tabindex="-1"></a>var.delta.tmax <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(derivs<span class="sc">%*%</span> vcv <span class="sc">%*%</span> derivs)</span>
<span id="cb107-4"><a href="error-propagation.html#cb107-4" tabindex="-1"></a>se.delta.tmax <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var.delta.tmax)</span>
<span id="cb107-5"><a href="error-propagation.html#cb107-5" tabindex="-1"></a></span>
<span id="cb107-6"><a href="error-propagation.html#cb107-6" tabindex="-1"></a><span class="co"># 95% CI:</span></span>
<span id="cb107-7"><a href="error-propagation.html#cb107-7" tabindex="-1"></a>tmax.delta.CI <span class="ot">&lt;-</span> (tmax.a<span class="sc">-</span>tmax.b) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))<span class="sc">*</span>se.delta.tmax</span>
<span id="cb107-8"><a href="error-propagation.html#cb107-8" tabindex="-1"></a>tmax.delta.CI</span></code></pre></div>
<pre><code>## [1] -6.824592 -5.663979</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="error-propagation.html#cb109-1" tabindex="-1"></a><span class="co"># compare to the sampling 95% CI:</span></span>
<span id="cb109-2"><a href="error-propagation.html#cb109-2" tabindex="-1"></a><span class="fu">quantile</span>(delta.tmaxs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##      2.5%     97.5% 
## -6.853705 -5.654158</code></pre>
<p>Again close enough!</p>
<p>We proceed in a similar fashion for the maximum values, first defining appropriate functions and then using the machinery from above to calculate CIs:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="error-propagation.html#cb111-1" tabindex="-1"></a>eta.max.a.fun <span class="ot">&lt;-</span> <span class="cf">function</span>(beta<span class="fl">.0</span>,beta.B,beta.time,beta.Bxtime,beta.time2,beta.Bxtime2){</span>
<span id="cb111-2"><a href="error-propagation.html#cb111-2" tabindex="-1"></a>  tmax.a <span class="ot">&lt;-</span> <span class="sc">-</span> beta.time<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>beta.time2)</span>
<span id="cb111-3"><a href="error-propagation.html#cb111-3" tabindex="-1"></a>  beta<span class="fl">.0</span> <span class="sc">+</span> beta.time<span class="sc">*</span>tmax.a <span class="sc">+</span> beta.time2<span class="sc">*</span>tmax.a<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb111-4"><a href="error-propagation.html#cb111-4" tabindex="-1"></a>}</span>
<span id="cb111-5"><a href="error-propagation.html#cb111-5" tabindex="-1"></a></span>
<span id="cb111-6"><a href="error-propagation.html#cb111-6" tabindex="-1"></a>eta.max.b.fun <span class="ot">&lt;-</span> <span class="cf">function</span>(beta<span class="fl">.0</span>,beta.B,beta.time,beta.Bxtime,beta.time2,beta.Bxtime2){</span>
<span id="cb111-7"><a href="error-propagation.html#cb111-7" tabindex="-1"></a>  tmax.b <span class="ot">&lt;-</span> <span class="sc">-</span> (beta.time<span class="sc">+</span>beta.Bxtime)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(beta.time2<span class="sc">+</span>beta.Bxtime2))</span>
<span id="cb111-8"><a href="error-propagation.html#cb111-8" tabindex="-1"></a>  beta<span class="fl">.0</span> <span class="sc">+</span> beta.B <span class="sc">+</span> (beta.time<span class="sc">+</span>beta.Bxtime)<span class="sc">*</span>tmax.b <span class="sc">+</span> (beta.time2<span class="sc">+</span>beta.Bxtime2)<span class="sc">*</span>tmax.b<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb111-9"><a href="error-propagation.html#cb111-9" tabindex="-1"></a>}</span>
<span id="cb111-10"><a href="error-propagation.html#cb111-10" tabindex="-1"></a></span>
<span id="cb111-11"><a href="error-propagation.html#cb111-11" tabindex="-1"></a>delta.eta.max.fun <span class="ot">&lt;-</span> <span class="cf">function</span>(beta<span class="fl">.0</span>,beta.B,beta.time,beta.Bxtime,beta.time2,beta.Bxtime2){</span>
<span id="cb111-12"><a href="error-propagation.html#cb111-12" tabindex="-1"></a>  tmax.a <span class="ot">&lt;-</span> <span class="sc">-</span> beta.time<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>beta.time2)</span>
<span id="cb111-13"><a href="error-propagation.html#cb111-13" tabindex="-1"></a>  tmax.b <span class="ot">&lt;-</span> <span class="sc">-</span> (beta.time<span class="sc">+</span>beta.Bxtime)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>(beta.time2<span class="sc">+</span>beta.Bxtime2))</span>
<span id="cb111-14"><a href="error-propagation.html#cb111-14" tabindex="-1"></a>  eta.max.a <span class="ot">&lt;-</span> beta<span class="fl">.0</span> <span class="sc">+</span> beta.time<span class="sc">*</span>tmax.a <span class="sc">+</span> beta.time2<span class="sc">*</span>tmax.a<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb111-15"><a href="error-propagation.html#cb111-15" tabindex="-1"></a>  eta.max.b <span class="ot">&lt;-</span> beta<span class="fl">.0</span> <span class="sc">+</span> beta.B <span class="sc">+</span> (beta.time<span class="sc">+</span>beta.Bxtime)<span class="sc">*</span>tmax.b <span class="sc">+</span> (beta.time2<span class="sc">+</span>beta.Bxtime2)<span class="sc">*</span>tmax.b<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb111-16"><a href="error-propagation.html#cb111-16" tabindex="-1"></a>  eta.max.a <span class="sc">-</span> eta.max.b</span>
<span id="cb111-17"><a href="error-propagation.html#cb111-17" tabindex="-1"></a>}</span>
<span id="cb111-18"><a href="error-propagation.html#cb111-18" tabindex="-1"></a></span>
<span id="cb111-19"><a href="error-propagation.html#cb111-19" tabindex="-1"></a>calc.CI <span class="ot">&lt;-</span> <span class="cf">function</span>(mod,func){</span>
<span id="cb111-20"><a href="error-propagation.html#cb111-20" tabindex="-1"></a>  expval <span class="ot">&lt;-</span> <span class="fu">func</span>(<span class="at">beta.0=</span><span class="fu">coef</span>(mod)[<span class="dv">1</span>],<span class="at">beta.B=</span><span class="fu">coef</span>(mod)[<span class="dv">2</span>],</span>
<span id="cb111-21"><a href="error-propagation.html#cb111-21" tabindex="-1"></a>         <span class="at">beta.time=</span><span class="fu">coef</span>(mod)[<span class="dv">3</span>],<span class="at">beta.time2=</span><span class="fu">coef</span>(mod)[<span class="dv">4</span>],</span>
<span id="cb111-22"><a href="error-propagation.html#cb111-22" tabindex="-1"></a>         <span class="at">beta.Bxtime=</span><span class="fu">coef</span>(mod)[<span class="dv">5</span>],<span class="at">beta.Bxtime2=</span><span class="fu">coef</span>(mod)[<span class="dv">6</span>])</span>
<span id="cb111-23"><a href="error-propagation.html#cb111-23" tabindex="-1"></a></span>
<span id="cb111-24"><a href="error-propagation.html#cb111-24" tabindex="-1"></a>  terms <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;beta.0&quot;</span>,<span class="st">&quot;beta.B&quot;</span>,<span class="st">&quot;beta.time&quot;</span>,<span class="st">&quot;beta.time2&quot;</span>,<span class="st">&quot;beta.Bxtime&quot;</span>,<span class="st">&quot;beta.Bxtime2&quot;</span>)</span>
<span id="cb111-25"><a href="error-propagation.html#cb111-25" tabindex="-1"></a>  derivs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="fu">length</span>(terms))</span>
<span id="cb111-26"><a href="error-propagation.html#cb111-26" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(terms)){</span>
<span id="cb111-27"><a href="error-propagation.html#cb111-27" tabindex="-1"></a>  derfun <span class="ot">&lt;-</span> <span class="fu">Deriv</span>(func,terms[i])</span>
<span id="cb111-28"><a href="error-propagation.html#cb111-28" tabindex="-1"></a>  derivs[i] <span class="ot">&lt;-</span> <span class="fu">derfun</span>(<span class="at">beta.0=</span><span class="fu">coef</span>(mod)[<span class="dv">1</span>],<span class="at">beta.B=</span><span class="fu">coef</span>(mod)[<span class="dv">2</span>],</span>
<span id="cb111-29"><a href="error-propagation.html#cb111-29" tabindex="-1"></a>         <span class="at">beta.time=</span><span class="fu">coef</span>(mod)[<span class="dv">3</span>],<span class="at">beta.time2=</span><span class="fu">coef</span>(mod)[<span class="dv">4</span>],</span>
<span id="cb111-30"><a href="error-propagation.html#cb111-30" tabindex="-1"></a>         <span class="at">beta.Bxtime=</span><span class="fu">coef</span>(mod)[<span class="dv">5</span>],<span class="at">beta.Bxtime2=</span><span class="fu">coef</span>(mod)[<span class="dv">6</span>])</span>
<span id="cb111-31"><a href="error-propagation.html#cb111-31" tabindex="-1"></a>  }</span>
<span id="cb111-32"><a href="error-propagation.html#cb111-32" tabindex="-1"></a>  vcv <span class="ot">&lt;-</span> <span class="fu">vcov</span>(mod)</span>
<span id="cb111-33"><a href="error-propagation.html#cb111-33" tabindex="-1"></a>  var.val <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(derivs<span class="sc">%*%</span> vcv <span class="sc">%*%</span> derivs)</span>
<span id="cb111-34"><a href="error-propagation.html#cb111-34" tabindex="-1"></a>  se.val <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var.val)</span>
<span id="cb111-35"><a href="error-propagation.html#cb111-35" tabindex="-1"></a></span>
<span id="cb111-36"><a href="error-propagation.html#cb111-36" tabindex="-1"></a><span class="co"># 95% CI:</span></span>
<span id="cb111-37"><a href="error-propagation.html#cb111-37" tabindex="-1"></a>  expval <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))<span class="sc">*</span>se.val</span>
<span id="cb111-38"><a href="error-propagation.html#cb111-38" tabindex="-1"></a>}</span>
<span id="cb111-39"><a href="error-propagation.html#cb111-39" tabindex="-1"></a></span>
<span id="cb111-40"><a href="error-propagation.html#cb111-40" tabindex="-1"></a><span class="co"># CI for eta.max.a:</span></span>
<span id="cb111-41"><a href="error-propagation.html#cb111-41" tabindex="-1"></a><span class="fu">calc.CI</span>(m1,eta.max.a.fun)</span></code></pre></div>
<pre><code>## [1] 2.806549 3.262232</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="error-propagation.html#cb113-1" tabindex="-1"></a><span class="co"># compare to the sampling 95% CI:</span></span>
<span id="cb113-2"><a href="error-propagation.html#cb113-2" tabindex="-1"></a><span class="fu">quantile</span>(eta.max.as,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 2.811468 3.266305</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="error-propagation.html#cb115-1" tabindex="-1"></a><span class="co"># CI for eta.max.b:</span></span>
<span id="cb115-2"><a href="error-propagation.html#cb115-2" tabindex="-1"></a><span class="fu">calc.CI</span>(m1,eta.max.b.fun)</span></code></pre></div>
<pre><code>## [1] 2.996256 3.383819</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="error-propagation.html#cb117-1" tabindex="-1"></a><span class="co"># compare to the sampling 95% CI:</span></span>
<span id="cb117-2"><a href="error-propagation.html#cb117-2" tabindex="-1"></a><span class="fu">quantile</span>(eta.max.bs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 2.998823 3.387557</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="error-propagation.html#cb119-1" tabindex="-1"></a><span class="do">## CI for the difference:</span></span>
<span id="cb119-2"><a href="error-propagation.html#cb119-2" tabindex="-1"></a><span class="co"># CI for eta.max.b:</span></span>
<span id="cb119-3"><a href="error-propagation.html#cb119-3" tabindex="-1"></a><span class="fu">calc.CI</span>(m1,delta.eta.max.fun)</span></code></pre></div>
<pre><code>## [1] -0.4547507  0.1434563</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="error-propagation.html#cb121-1" tabindex="-1"></a><span class="co"># compare to the sampling 95% CI:</span></span>
<span id="cb121-2"><a href="error-propagation.html#cb121-2" tabindex="-1"></a><span class="fu">quantile</span>(delta.maxs,<span class="at">probs=</span><span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##       2.5%      97.5% 
## -0.4534911  0.1446363</code></pre>
</div>
<div id="conclusion" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Conclusion<a href="error-propagation.html#conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The sampling and delta method gave near identical results. We conclude that for the fitted model, the maximum number of visitors at truck A occurs at 11.9 with a 95% CI of [11.55, 12.34] and for truck B at time 18.2 with a 95% CI of [17.77, 18.61]. The difference in timing of the maxima between the two trucks is -6.2 with a 95% CI of [-6.82, -5.66]. Here, negative numbers indicate that the maximum occurred first in truck A.</p>
<p>The maximum values themselves on the log scale were for truck A 3.03 with a 95% CI of [2.81, 3.26] and for truck B 3.19 with a 95% CI of [3, 3.38]. The difference in between maxima between the two trucks is -0.16 with a 95% CI of [-0.45, 0.14]. Here, negative values would indicate that truck B has a higher maximum than truck A.</p>
<p>On the observable scale (i.e. actual counts), the highest number of visitors at truck A was 20.79 with a 95% CI of [16.55, 26.11] and for truck B 24.29 with a 95% CI of [20.01, 29.48]. The relative difference between the maximum number of visitors between the two trucks was 0.86 with a 95% CI of [0.63, 1.15]. This means that the maximum number of visitors for truck A was 0.86 x the maximum number of visitors for truck B.</p>

</div>
</div>
<h3>Bibliography<a href="bibliography.html#bibliography" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-deltamethod" class="csl-entry">
Cooch, E., and G. White, eds. 2024. <span>“Appendix b – the <span>‘Delta Method’</span> ...”</span> In <em>Program MARK – a Gentle Introduction</em>. <a href="http://www.phidot.org/software/mark/docs/book/" class="uri">http://www.phidot.org/software/mark/docs/book/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="transforming-posterior-samples.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="proportion-of-negative-values-from-a-normal-distribution.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "toolbar": {
    "position": "static"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
